export interface IUser {
    id? : number,
    username? : string,
    password? : string,
    email? : string,
    phone? : string,
    name? : string,
    job? : string,
    postdate? : string,
    modDate? : string,
    articles? : number,
    json?: IUser,
    array? : IUser[],
    message? : string,
}